// import "./App.css";

import { Routes, Route } from "react-router-dom";
import { Container } from "react-bootstrap";
import Header from "./components/Header.jsx";
import HomePage from "./pages/Home.jsx";
import AboutPage from "./pages/About.jsx";
import BlogPage from "./pages/Blog.jsx";
import CodePage from "./pages/Code.jsx";
import MusicPage from "./pages/Music.jsx";
import ReadingPage from "./pages/Reading.jsx";
import JournalPage from "./pages/Journal.jsx";
import { findRecentPages } from "./components/RecentPagesDisplay.jsx";

const APP_MAX_WIDTH = "900px";

// TODO: this can be generated by vite by globbing in pages/
const PAGES = [
  {
    name: "Home",
    path: "/",
    component: HomePage,
  },
  {
    name: "About",
    path: "/about",
    component: AboutPage,
  },
  // {
  //   name: "Blog",
  //   path: "/blog",
  //   component: BlogPage,
  // },
  // {
  //   name: "Code",
  //   path: "/code",
  //   component: CodePage,
  // },
  // {
  //   name: "Music",
  //   path: "/music",
  //   component: MusicPage,
  // },
  // {
  //   name: "Reading",
  //   path: "/reading",
  //   component: ReadingPage,
  // },
  {
    name: "Journal",
    path: "/journal",
    component: JournalPage,
  },
];

function getRoute(name, path, component) {
  return <Route key={name} path={path} element={component()} />;
}

function getSinglePageRoute(urlPath, module) {
  console.log(urlPath);
  return <Route key={urlPath} path={urlPath} element={module.default()} />;
}

function App() {
  const singlePages = findRecentPages("/src/single-pages", null);
  console.log(singlePages);
  return (
    <Container style={{ maxWidth: APP_MAX_WIDTH }}>
      <Header pages={PAGES} />
      <Routes>
        {PAGES.map((page) => getRoute(page.name, page.path, page.component))}
        {singlePages.map((page) =>
          getSinglePageRoute(page.urlPath, page.module),
        )}
      </Routes>
    </Container>
  );
}

export default App;
